version: '0.1'

services:
  europe-instance:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alex1999
    ports:
      - 5437:5432
    volumes:
      - ./data:/var/lib/postgresql/data1

  asia-instance:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alex1999
    ports:
      - 5434:5432
    volumes:
      - ./data:/var/lib/postgresql/data2
    
  north_america-instance:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alex1999
    ports:
      - 5435:5432
    volumes:
      - ./data:/var/lib/postgresql/data3
    
  oceania-instance:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alex1999
    ports:
      - 5436:5432
    volumes:
      - ./data:/var/lib/postgresql/data4